server:
  port: 7101

spring:
  application:
    name: hello-service-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:logback.xml


